platform :ios, '11.0'

use_frameworks!

target 'MeteorDDP_Example' do
  pod 'MeteorDDP', :path => '../'

  target 'MeteorDDP_Tests' do
    inherit! :search_paths
    
  end
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
